image: python:3.6-slim

variables:
  COACH_TEMP_IMAGE: $CI_REGISTRY_IMAGE/ci/coach:$CI_COMMIT_SHORT_SHA
  BOT_TEMP_IMAGE: $CI_REGISTRY_IMAGE/ci/bot:$CI_COMMIT_SHORT_SHA

stages:
  - test style
  - build requirements
  - test stories
  - build coach
  - build


test style:
  stage: test style
  script:
    - pip -V
    - python -V
    - pip install -r requirements.txt
    - flake8 --exclude venv


test stories:
  stage: test stories
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker build . -f docker/coach.Dockerfile -t lappis/coach:boilerplate # Builds lappis/coach:boilerplate
    - docker build -f docker/bot.Dockerfile -t $BOT_TEMP_IMAGE . # It uses lappis/coach:boilerplate built locally
    - docker run --rm $BOT_TEMP_IMAGE make test-stories
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker tag lappis/coach:boilerplate $COACH_TEMP_IMAGE # Retags lappis/coach:boilerplate to temp image
    - docker push $COACH_TEMP_IMAGE # Pushes temp image to the gitlab registry (it will be pulled from gitlab and pushed to Dockerhub later)
    - docker push $BOT_TEMP_IMAGE


build requirements:
  stage: build requirements
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - cd ./docker
    - ./build-base.sh publish
  only:
    refs:
      - master
    changes:
      - ./docker/requirements.txt
  environment: homolog


build coach:
  stage: build coach
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - docker pull $COACH_TEMP_IMAGE
    - docker tag $COACH_TEMP_IMAGE lappis/coach:boilerplate
    - docker push lappis/coach:boilerplate
  only:
    - master
  environment: homolog


build bot:
  stage: build
  image: docker
  tags:
    - docker
  services:
    - docker:dind
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
    - docker pull $BOT_TEMP_IMAGE
    - docker tag $BOT_TEMP_IMAGE lappis/bot:boilerplate
    - docker push lappis/bot:boilerplate
  only:
    - master
  environment: homolog
