# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build_bot

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        # Added "gast=0.2.2" as a workarround because of a Tensorflow issue, should be removed soon
        python -m pip install --upgrade pip gast==0.2.2
        pip install flake8 pytest
        if [ -f bot/requirements.txt ]; then pip install --use-deprecated=legacy-resolver -r bot/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test Rasa version
      run: |
        rasa --version 
    - name: Rasa train
      run: |
        cd bot/
        make train
    - name: Test Rasa bot
      run: |
        cd bot/
        make test
